name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Set the branch you want to deploy on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Heroku Container Registry
      run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build, tag, and push Docker image
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --build-arg AWS_DEFAULT_REGION=us-east-1 .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release the image
      run: |
        heroku stack:set container -a ${{ secrets.HEROKU_APP_NAME }}
        heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
        heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
